// kcal/macros are per-portion estimates at the "regular" size; small ≈
// ×0.75, large ≈ ×1.35, rounded — close enough for planning, not medical.
const MEAL_LIBRARY = [
  // ── 10 MIN — no-cook / assembly ──────────────────────────────────────
  { id:'charcuteria', name:'Charcutería board', prep:10, proteinType:'cured', tags:['no-cook','protein'],
    ingredients:['Jamón serrano (Mercadona, loncheado)','Lomo embuchado o salchichón','Queso semicurado en cuña','Picos o tostadas integrales','Tomates cherry','Aceitunas (Mercadona, botella)'],
    kcal:520, protein:28, carbs:24, fat:34, gazpacho:true },
  { id:'tortilla-lista', name:'Tortilla de patata (ya hecha) + ensalada', prep:8, proteinType:'egg', tags:['no-cook','classic'],
    ingredients:['Tortilla de patata Hacendado (refrigerada)','Lechuga variada en bolsa','Tomate','Cebolla morada','Aceite de oliva virgen extra'],
    kcal:480, protein:18, carbs:32, fat:30, gazpacho:true },
  { id:'salmon-ahumado', name:'Salmón ahumado, queso fresco y tostas', prep:8, proteinType:'fish', tags:['no-cook','protein','omega3'],
    ingredients:['Salmón ahumado Hacendado','Queso fresco de Burgos','Pan de molde integral o tostas','Aguacate','Limón'],
    kcal:470, protein:30, carbs:26, fat:26, gazpacho:true },
  { id:'atun-garbanzo', name:'Ensalada de garbanzos y atún', prep:10, proteinType:'legume', tags:['no-cook','protein','legume'],
    ingredients:['Garbanzos cocidos (bote Mercadona)','Atún en aceite de oliva (lata)','Pimiento rojo','Cebolla morada','Aceitunas','Aceite de oliva virgen extra y vinagre'],
    kcal:510, protein:32, carbs:42, fat:20, gazpacho:true },
  { id:'queso-membrillo', name:'Tabla de quesos, membrillo y nueces', prep:8, proteinType:'cheese', tags:['no-cook','light'],
    ingredients:['Queso curado o manchego en cuña','Membrillo Hacendado','Nueces peladas','Picos integrales','Uvas'],
    kcal:500, protein:20, carbs:38, fat:28, gazpacho:true },
  { id:'huevos-rellenos', name:'Huevos rellenos y ensalada de tomate', prep:10, proteinType:'egg', tags:['no-cook','protein'],
    ingredients:['Huevos cocidos (bandeja Mercadona, ya cocidos)','Atún o mahonesa Hacendado','Tomate de ensalada','Aceite de oliva virgen extra','Orégano'],
    kcal:430, protein:24, carbs:14, fat:32, gazpacho:true },
  { id:'pollo-asado-bolsa', name:'Pollo asado (rotisería) con ensalada', prep:10, proteinType:'poultry', tags:['no-cook','protein'],
    ingredients:['Pollo asado entero (sección rotisería Mercadona)','Lechuga variada en bolsa','Zanahoria rallada','Maíz dulce (lata)','Aceite de oliva virgen extra'],
    kcal:560, protein:42, carbs:18, fat:30, gazpacho:true },
  { id:'jamon-melon', name:'Jamón con melón y burrata', prep:8, proteinType:'cured', tags:['no-cook','light','summer'],
    ingredients:['Jamón serrano loncheado','Melón (medio, en temporada)','Burrata o mozzarella fresca','Albahaca','Aceite de oliva virgen extra'],
    kcal:440, protein:22, carbs:24, fat:28, gazpacho:true },

  // ── 20–30 MIN — one-pan / stovetop ───────────────────────────────────
  { id:'tortilla-casera', name:'Tortilla de patata casera', prep:25, proteinType:'egg', tags:['cooked','classic'],
    ingredients:['Patatas','Huevos (Mercadona, jaula campera)','Cebolla','Aceite de oliva virgen extra','Sal'],
    kcal:540, protein:20, carbs:38, fat:32, gazpacho:true },
  { id:'pasta-tomate-atun', name:'Pasta con tomate, atún y aceitunas', prep:20, proteinType:'fish', tags:['cooked','quick'],
    ingredients:['Pasta (Hacendado)','Tomate frito Hacendado','Atún en aceite de oliva (lata)','Aceitunas negras','Ajo','Albahaca seca'],
    kcal:580, protein:28, carbs:68, fat:18, gazpacho:true },
  { id:'arroz-verduras-gambas', name:'Arroz con verduras y gambas', prep:25, proteinType:'seafood', tags:['cooked','seafood'],
    ingredients:['Arroz redondo (Hacendado)','Gambas peladas congeladas','Pimiento','Calabacín','Cebolla','Caldo de pescado o de verduras','Ajo y pimentón'],
    kcal:530, protein:30, carbs:60, fat:14, gazpacho:true },
  { id:'lentejas-rapidas', name:'Lentejas estofadas con chorizo', prep:25, proteinType:'legume', tags:['cooked','legume','warming'],
    ingredients:['Lentejas cocidas (bote Mercadona)','Chorizo Hacendado','Zanahoria','Cebolla','Pimentón','Tomate frito'],
    kcal:560, protein:30, carbs:48, fat:24, gazpacho:false },
  { id:'pollo-plancha-verduras', name:'Pollo a la plancha con verduras salteadas', prep:20, proteinType:'poultry', tags:['cooked','protein','quick'],
    ingredients:['Pechuga de pollo (Mercadona)','Calabacín','Pimiento','Cebolla','Aceite de oliva virgen extra','Especias al gusto'],
    kcal:480, protein:42, carbs:18, fat:24, gazpacho:true },
  { id:'salmon-plancha-patata', name:'Salmón a la plancha con patata al horno', prep:30, proteinType:'fish', tags:['cooked','protein','omega3'],
    ingredients:['Lomos de salmón (Mercadona)','Patatas','Limón','Eneldo o perejil','Aceite de oliva virgen extra'],
    kcal:560, protein:38, carbs:34, fat:26, gazpacho:true },
  { id:'revuelto-gambas-setas', name:'Revuelto de gambas y setas', prep:15, proteinType:'seafood', tags:['cooked','protein','quick'],
    ingredients:['Huevos','Gambas peladas congeladas','Setas o champiñones (bandeja)','Ajo','Perejil','Aceite de oliva virgen extra'],
    kcal:420, protein:30, carbs:8, fat:28, gazpacho:true },
  { id:'merluza-papillote', name:'Merluza al papillote con verduras', prep:25, proteinType:'fish', tags:['cooked','protein','light'],
    ingredients:['Filetes de merluza (Mercadona, congelada)','Calabacín','Tomate','Cebolla','Limón','Aceite de oliva virgen extra'],
    kcal:420, protein:36, carbs:16, fat:20, gazpacho:true },
  { id:'fajitas-pollo', name:'Fajitas de pollo con pimientos', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Pechuga de pollo','Tortillas de trigo Hacendado','Pimiento tricolor','Cebolla','Especias fajita','Queso rallado'],
    kcal:610, protein:38, carbs:52, fat:24, gazpacho:true },
  { id:'arroz-pollo-curry', name:'Arroz con pollo al curry', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Arroz basmati Hacendado','Pechuga de pollo','Leche de coco','Curry en polvo','Cebolla','Guisantes congelados'],
    kcal:600, protein:36, carbs:62, fat:20, gazpacho:false },
  { id:'pisto-huevo', name:'Pisto manchego con huevo a la plancha', prep:30, proteinType:'egg', tags:['cooked','veg-forward'],
    ingredients:['Calabacín','Berenjena','Pimiento','Tomate frito','Cebolla','Huevos'],
    kcal:440, protein:18, carbs:30, fat:24, gazpacho:true },
  { id:'tacos-pescado', name:'Tacos de pescado con repollo', prep:25, proteinType:'fish', tags:['cooked','seafood'],
    ingredients:['Filetes de merluza o abadejo (Mercadona)','Tortillas de maíz o trigo','Repollo o lechuga','Yogur o lima','Pimentón'],
    kcal:520, protein:32, carbs:46, fat:20, gazpacho:true },

  // ── 35+ MIN — slow ones, kept to a minimum ──────────────────────────
  { id:'paella-mixta', name:'Paella mixta', prep:45, proteinType:'seafood', tags:['cooked','slow','weekend'],
    ingredients:['Arroz redondo (Hacendado)','Pollo','Gambas o mejillones','Judía verde plana','Pimiento rojo','Caldo de pollo o pescado','Azafrán o colorante'],
    kcal:640, protein:34, carbs:66, fat:22, gazpacho:true },
  { id:'lentejas-tradicionales', name:'Lentejas con verduras (a fuego lento)', prep:40, proteinType:'legume', tags:['cooked','slow','legume','batch'],
    ingredients:['Lentejas secas (Hacendado)','Zanahoria','Patata','Cebolla','Pimentón','Laurel'],
    kcal:520, protein:26, carbs:62, fat:14, gazpacho:false },

  // ── NEW MEALS — 10 MIN ───────────────────────────────────────────────
  { id:'ensalada-pollo-mango', name:'Ensalada de pollo y mango', prep:10, proteinType:'poultry', tags:['no-cook','light','summer'],
    ingredients:['Pechuga de pollo cocida (Mercadona, envasada)','Mango','Lechuga variada en bolsa','Aguacate','Lima','Aceite de oliva virgen extra'],
    kcal:460, protein:34, carbs:28, fat:20, gazpacho:false },
  { id:'conservas-mar', name:'Tabla de conservas del mar', prep:8, proteinType:'fish', tags:['no-cook','protein','omega3'],
    ingredients:['Boquerones en vinagre (Mercadona)','Mejillones en escabeche (lata)','Berberechos al natural (lata)','Tostadas integrales','Tomate de ramellet','Aceite de oliva virgen extra'],
    kcal:430, protein:32, carbs:22, fat:20, gazpacho:true },
  { id:'ensalada-garbanzos-espinacas', name:'Ensalada de garbanzos, espinacas y feta', prep:10, proteinType:'legume', tags:['no-cook','protein','legume'],
    ingredients:['Garbanzos cocidos (bote Mercadona)','Espinacas baby (bolsa)','Queso feta (Mercadona)','Tomates cherry','Pepino','Aceite de oliva virgen extra y limón'],
    kcal:490, protein:26, carbs:44, fat:22, gazpacho:true },
  { id:'wrap-pavo-aguacate', name:'Wrap de pavo, aguacate y queso', prep:8, proteinType:'poultry', tags:['no-cook','quick'],
    ingredients:['Pechuga de pavo loncheada (Mercadona)','Tortilla de trigo Hacendado','Aguacate','Queso en lonchas','Lechuga','Mostaza o mahonesa light'],
    kcal:500, protein:36, carbs:38, fat:22, gazpacho:false },
  { id:'ensalada-atun-pasta', name:'Ensalada de pasta fría con atún', prep:10, proteinType:'fish', tags:['no-cook','quick'],
    ingredients:['Pasta cocida (sobrante o Mercadona lista)','Atún en aceite de oliva (lata)','Maíz dulce (lata)','Tomate','Aceitunas','Aceite de oliva virgen extra'],
    kcal:540, protein:28, carbs:58, fat:18, gazpacho:true },
  { id:'bocadillo-serrano-tomate', name:'Bocadillo de jamón serrano con tomate', prep:8, proteinType:'cured', tags:['no-cook','classic'],
    ingredients:['Pan de barra o chapata (Mercadona)','Jamón serrano loncheado','Tomate maduro para frotar','Aceite de oliva virgen extra','Sal'],
    kcal:480, protein:26, carbs:46, fat:18, gazpacho:true },
  { id:'ensalada-lentejas-feta', name:'Ensalada de lentejas y queso feta', prep:10, proteinType:'legume', tags:['no-cook','protein'],
    ingredients:['Lentejas cocidas (bote Mercadona)','Queso feta','Tomate cherry','Pepinillos','Cebolla morada','Vinagreta de mostaza'],
    kcal:470, protein:24, carbs:46, fat:18, gazpacho:true },
  { id:'tosta-sardinas', name:'Tostas de sardinas con pimiento asado', prep:8, proteinType:'fish', tags:['no-cook','omega3'],
    ingredients:['Sardinas en aceite de oliva (lata Hacendado)','Tostadas integrales','Pimiento rojo asado (bote Mercadona)','Tomate cherry','Perejil fresco'],
    kcal:440, protein:28, carbs:26, fat:22, gazpacho:true },
  { id:'ensalada-caprese', name:'Ensalada caprese con anchoas', prep:8, proteinType:'fish', tags:['no-cook','light','summer'],
    ingredients:['Mozzarella fresca','Tomate de ensalada en rodajas','Anchoas en aceite (lata)','Albahaca fresca','Aceite de oliva virgen extra','Sal Maldon'],
    kcal:420, protein:24, carbs:10, fat:32, gazpacho:true },
  { id:'bowlquinoa-pollo', name:'Bowl de quinoa y pollo asado', prep:10, proteinType:'poultry', tags:['no-cook','protein','balanced'],
    ingredients:['Quinoa cocida (Mercadona, bolsita lista)','Pechuga de pollo asado (envasada)','Aguacate','Tomates cherry','Maíz dulce (lata)','Limón y aceite'],
    kcal:510, protein:38, carbs:42, fat:18, gazpacho:false },
  { id:'ensalada-repollo-salmon', name:'Ensalada de repollo con salmón ahumado', prep:10, proteinType:'fish', tags:['no-cook','omega3','light'],
    ingredients:['Repollo o col lombarda (Mercadona)','Salmón ahumado Hacendado','Zanahoria rallada','Manzana verde','Vinagreta de mostaza y miel'],
    kcal:430, protein:28, carbs:24, fat:22, gazpacho:false },
  { id:'hummus-pollo-pita', name:'Hummus casero con pollo y pan pita', prep:10, proteinType:'poultry', tags:['no-cook','protein'],
    ingredients:['Hummus Mercadona','Pechuga de pollo cocida loncheada','Pan pita integral','Pepino','Tomate','Pimentón dulce'],
    kcal:490, protein:36, carbs:40, fat:18, gazpacho:false },

  // ── NEW MEALS — 20–30 MIN ────────────────────────────────────────────
  { id:'pechuga-limon-alcaparras', name:'Pechuga de pollo al limón con alcaparras', prep:20, proteinType:'poultry', tags:['cooked','protein','quick'],
    ingredients:['Pechuga de pollo (Mercadona)','Limón','Alcaparras (bote)','Ajo','Vino blanco','Aceite de oliva virgen extra'],
    kcal:460, protein:44, carbs:6, fat:24, gazpacho:true },
  { id:'gambas-ajo', name:'Gambas al ajillo con pan', prep:12, proteinType:'seafood', tags:['cooked','quick','classic'],
    ingredients:['Gambas peladas (Mercadona, congeladas)','Ajo','Guindilla seca','Aceite de oliva virgen extra','Pan de barra para acompañar'],
    kcal:440, protein:32, carbs:22, fat:24, gazpacho:true },
  { id:'tortilla-francesa-ensalada', name:'Tortilla francesa rellena de espinacas y queso', prep:12, proteinType:'egg', tags:['cooked','quick'],
    ingredients:['Huevos','Espinacas frescas (bolsa)','Queso rallado Hacendado','Aceite de oliva virgen extra','Lechuga de acompañamiento'],
    kcal:420, protein:28, carbs:10, fat:28, gazpacho:true },
  { id:'pasta-carbonara-ligera', name:'Pasta carbonara ligera', prep:20, proteinType:'cured', tags:['cooked','quick','classic'],
    ingredients:['Pasta (Hacendado)','Panceta o bacon Hacendado','Huevos','Queso parmesano rallado','Pimienta negra','Sal'],
    kcal:610, protein:30, carbs:64, fat:26, gazpacho:false },
  { id:'merluza-salsa-verde', name:'Merluza en salsa verde', prep:25, proteinType:'fish', tags:['cooked','protein','classic'],
    ingredients:['Lomos de merluza (Mercadona)','Ajo','Perejil fresco','Vino blanco','Caldo de pescado','Harina','Aceite de oliva virgen extra'],
    kcal:400, protein:38, carbs:12, fat:18, gazpacho:true },
  { id:'arroz-negro-sepia', name:'Arroz negro con sepia', prep:30, proteinType:'seafood', tags:['cooked','weekend','seafood'],
    ingredients:['Arroz redondo (Hacendado)','Sepia o calamar (Mercadona, fresco o congelado)','Tinta de calamar (sobrecito)','Cebolla','Ajo','Caldo de pescado','Tomate','Alioli Mercadona'],
    kcal:560, protein:32, carbs:62, fat:16, gazpacho:false },
  { id:'pollo-pimientos-asados', name:'Muslos de pollo con pimientos asados', prep:30, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Muslos de pollo (Mercadona)','Pimientos tricolor','Cebolla','Ajo','Aceite de oliva virgen extra','Romero y tomillo'],
    kcal:540, protein:40, carbs:20, fat:32, gazpacho:true },
  { id:'espaguetis-almejas', name:'Espaguetis con almejas', prep:25, proteinType:'seafood', tags:['cooked','classic','seafood'],
    ingredients:['Espaguetis (Hacendado)','Almejas (Mercadona, congeladas)','Ajo','Perejil','Vino blanco','Aceite de oliva virgen extra','Guindilla'],
    kcal:530, protein:28, carbs:68, fat:14, gazpacho:false },
  { id:'garbanzos-espinacas-huevo', name:'Garbanzos con espinacas y huevo pochado', prep:20, proteinType:'legume', tags:['cooked','legume','veg-forward'],
    ingredients:['Garbanzos cocidos (bote Mercadona)','Espinacas frescas (bolsa)','Huevos','Ajo','Comino','Pimentón','Aceite de oliva virgen extra'],
    kcal:480, protein:28, carbs:46, fat:20, gazpacho:true },
  { id:'dorada-horno', name:'Dorada al horno con patatas panadera', prep:30, proteinType:'fish', tags:['cooked','protein','classic'],
    ingredients:['Dorada (Mercadona, fresca o congelada)','Patatas','Cebolla','Limón','Ajo','Aceite de oliva virgen extra','Vino blanco'],
    kcal:520, protein:38, carbs:36, fat:20, gazpacho:true },
  { id:'solomillo-cerdo-manzana', name:'Solomillo de cerdo con salsa de manzana', prep:25, proteinType:'pork', tags:['cooked','protein'],
    ingredients:['Solomillo de cerdo (Mercadona)','Manzana','Cebolla','Mostaza de Dijon','Nata para cocinar Hacendado','Aceite de oliva virgen extra'],
    kcal:530, protein:40, carbs:20, fat:28, gazpacho:false },
  { id:'alubias-chorizo', name:'Alubias blancas con chorizo', prep:20, proteinType:'legume', tags:['cooked','legume','warming'],
    ingredients:['Alubias blancas (bote Hacendado)','Chorizo Hacendado','Ajo','Pimentón','Tomate frito','Caldo de verduras','Laurel'],
    kcal:560, protein:28, carbs:52, fat:24, gazpacho:false },
  { id:'calamar-plancha', name:'Calamares a la plancha con alioli', prep:15, proteinType:'seafood', tags:['cooked','quick','seafood'],
    ingredients:['Anillas de calamar (Mercadona, congeladas)','Ajo','Perejil','Limón','Aceite de oliva virgen extra','Alioli Mercadona'],
    kcal:380, protein:30, carbs:12, fat:22, gazpacho:true },
  { id:'pavo-plancha-pure', name:'Filete de pavo a la plancha con puré', prep:20, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Filetes de pavo (Mercadona)','Puré de patatas instantáneo Hacendado','Cebolleta','Mantequilla','Leche','Sal y pimienta'],
    kcal:500, protein:42, carbs:36, fat:18, gazpacho:false },
  { id:'revuelto-esparragos-jamon', name:'Revuelto de espárragos trigueros y jamón', prep:15, proteinType:'egg', tags:['cooked','quick','protein'],
    ingredients:['Huevos','Espárragos trigueros (Mercadona)','Jamón serrano en taquitos','Ajo','Aceite de oliva virgen extra'],
    kcal:430, protein:30, carbs:8, fat:30, gazpacho:true },
  { id:'fideuà-rapida', name:'Fideuà rápida de gambas', prep:25, proteinType:'seafood', tags:['cooked','weekend','classic'],
    ingredients:['Fideos gordos para fideuà (Hacendado)','Gambas peladas congeladas','Calamar en anillas','Ajo','Tomate rallado','Caldo de pescado','Pimentón','Alioli'],
    kcal:580, protein:34, carbs:64, fat:16, gazpacho:false },
  { id:'pollo-cacahuete', name:'Salteado de pollo con salsa de cacahuete', prep:20, proteinType:'poultry', tags:['cooked','protein','quick'],
    ingredients:['Pechuga de pollo en tiras','Crema de cacahuete Hacendado','Salsa de soja','Ajo','Jengibre en polvo','Arroz jazmín (Hacendado)'],
    kcal:580, protein:44, carbs:46, fat:22, gazpacho:false },
  { id:'bacalao-tomate', name:'Bacalao a la vizcaína', prep:25, proteinType:'fish', tags:['cooked','classic','protein'],
    ingredients:['Lomos de bacalao desalado (Mercadona)','Tomate frito','Pimiento rojo','Cebolla','Ajo','Aceite de oliva virgen extra','Laurel'],
    kcal:440, protein:40, carbs:22, fat:18, gazpacho:true },
  { id:'tortilla-verduras', name:'Tortilla de verduras salteadas', prep:25, proteinType:'egg', tags:['cooked','veg-forward'],
    ingredients:['Huevos','Calabacín','Pimiento','Cebolla','Tomate cherry','Aceite de oliva virgen extra'],
    kcal:420, protein:20, carbs:22, fat:26, gazpacho:true },
  { id:'cerdo-verduras-soja', name:'Cerdo salteado con verduras y soja', prep:20, proteinType:'pork', tags:['cooked','quick','protein'],
    ingredients:['Lomo de cerdo en tiras (Mercadona)','Pimiento','Calabacín','Cebolla','Salsa de soja','Ajo','Aceite de girasol','Arroz o fideos de acompañamiento'],
    kcal:510, protein:38, carbs:36, fat:20, gazpacho:false },
  { id:'albondigas-tomate', name:'Albóndigas caseras en salsa de tomate', prep:30, proteinType:'beef', tags:['cooked','classic'],
    ingredients:['Carne picada mixta (Mercadona)','Huevo','Pan rallado','Ajo','Tomate frito Hacendado','Cebolla','Perejil','Aceite de oliva virgen extra'],
    kcal:560, protein:34, carbs:30, fat:32, gazpacho:true },
  { id:'pollo-tikka', name:'Pollo al estilo tikka masala', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Pechuga de pollo en dados','Yogur natural Hacendado','Tomate frito','Garam masala','Cúrcuma','Cebolla','Arroz basmati Hacendado'],
    kcal:570, protein:42, carbs:52, fat:18, gazpacho:false },
  { id:'ensalada-aguacate-langostinos', name:'Ensalada de aguacate y langostinos', prep:12, proteinType:'seafood', tags:['cooked','protein','light'],
    ingredients:['Langostinos cocidos (Mercadona)','Aguacate','Lechuga variada','Tomate cherry','Cebolla morada','Salsa rosa (mahonesa y ketchup)'],
    kcal:450, protein:28, carbs:18, fat:28, gazpacho:true },
  { id:'pasta-pesto-pollo', name:'Pasta con pesto y pollo a la plancha', prep:20, proteinType:'poultry', tags:['cooked','quick','protein'],
    ingredients:['Pasta (Hacendado)','Pechuga de pollo','Pesto Hacendado (bote)','Tomates cherry','Queso parmesano rallado'],
    kcal:590, protein:40, carbs:58, fat:22, gazpacho:false },
  { id:'huevos-rotos-jamon', name:'Huevos rotos con jamón y patatas fritas', prep:20, proteinType:'egg', tags:['cooked','classic','indulgente'],
    ingredients:['Huevos','Jamón serrano en lonchas','Patatas','Aceite de oliva virgen extra','Sal'],
    kcal:620, protein:28, carbs:44, fat:36, gazpacho:true },
  { id:'mejillones-vapor', name:'Mejillones al vapor con limón', prep:12, proteinType:'seafood', tags:['cooked','quick','seafood'],
    ingredients:['Mejillones frescos (Mercadona, malla)','Limón','Vino blanco','Laurel','Pan de acompañamiento'],
    kcal:380, protein:34, carbs:16, fat:10, gazpacho:true },
  { id:'pollo-mostaza-miel', name:'Pollo a la miel y mostaza', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Muslos o contramuslos de pollo (Mercadona)','Mostaza de Dijon','Miel Hacendado','Ajo','Aceite de oliva virgen extra','Romero'],
    kcal:530, protein:40, carbs:22, fat:28, gazpacho:true },
  { id:'bonito-pimiento-tomate', name:'Bonito en conserva con tomate y pimiento', prep:10, proteinType:'fish', tags:['no-cook','protein'],
    ingredients:['Bonito en aceite de oliva (lata Hacendado)','Tomate de ensalada','Pimiento verde italiano','Cebolla','Aceite de oliva virgen extra y vinagre','Pan de acompañamiento'],
    kcal:450, protein:30, carbs:22, fat:22, gazpacho:true },
  { id:'sopa-pescado', name:'Sopa de pescado y marisco', prep:25, proteinType:'fish', tags:['cooked','warming','classic'],
    ingredients:['Caldo de pescado (brik Hacendado)','Merluza en dados','Gambas peladas congeladas','Tomate frito','Cebolla','Ajo','Fideos sopa','Pimentón'],
    kcal:400, protein:32, carbs:38, fat:12, gazpacho:false },
  { id:'ternera-plancha-pisto', name:'Filete de ternera con pisto', prep:25, proteinType:'beef', tags:['cooked','protein','classic'],
    ingredients:['Filete de ternera (Mercadona)','Calabacín','Berenjena','Pimiento','Cebolla','Tomate frito Hacendado','Aceite de oliva virgen extra'],
    kcal:530, protein:38, carbs:24, fat:28, gazpacho:true },
  { id:'pasta-verduras-carbonara', name:'Pasta con verduras al estilo carbonara', prep:20, proteinType:'egg', tags:['cooked','veg-forward','quick'],
    ingredients:['Pasta (Hacendado)','Huevos','Calabacín','Espárragos verdes','Queso parmesano rallado','Pimienta negra','Aceite de oliva'],
    kcal:540, protein:26, carbs:64, fat:20, gazpacho:false },
  { id:'ensalada-boniato-pollo', name:'Ensalada de boniato asado y pollo', prep:30, proteinType:'poultry', tags:['cooked','balanced'],
    ingredients:['Boniato (Mercadona)','Pechuga de pollo','Rúcula o espinacas baby','Nueces peladas','Queso de cabra','Miel y vinagre balsámico'],
    kcal:520, protein:36, carbs:44, fat:20, gazpacho:false },
  { id:'hamburguesa-casera', name:'Hamburguesa casera con ensalada', prep:20, proteinType:'beef', tags:['cooked','protein'],
    ingredients:['Carne picada de ternera (Mercadona)','Pan de hamburguesa Hacendado','Lechuga','Tomate','Queso en lonchas','Ketchup y mostaza'],
    kcal:590, protein:36, carbs:42, fat:28, gazpacho:false },
  { id:'sepia-plancha-alioli', name:'Sepia a la plancha con alioli y patatas', prep:20, proteinType:'seafood', tags:['cooked','classic','seafood'],
    ingredients:['Sepia (Mercadona, fresca o congelada)','Patatas cocidas o al vapor','Ajo','Perejil','Limón','Alioli Mercadona','Aceite de oliva virgen extra'],
    kcal:470, protein:34, carbs:36, fat:18, gazpacho:true },
  { id:'crema-verduras-huevo', name:'Crema de verduras con huevo poché', prep:25, proteinType:'egg', tags:['cooked','light','warming'],
    ingredients:['Calabaza o calabacín (Mercadona)','Cebolla','Zanahoria','Caldo de verduras','Huevos','Aceite de oliva virgen extra','Nata ligera Hacendado'],
    kcal:380, protein:18, carbs:32, fat:20, gazpacho:false },
  { id:'conejo-tomate-ajo', name:'Conejo al ajillo con patatas', prep:30, proteinType:'poultry', tags:['cooked','classic'],
    ingredients:['Conejo troceado (Mercadona)','Ajo','Vino blanco','Patatas','Romero','Aceite de oliva virgen extra','Laurel'],
    kcal:510, protein:42, carbs:28, fat:22, gazpacho:true },
  { id:'berenjenas-rellenas', name:'Berenjenas rellenas de carne y tomate', prep:30, proteinType:'beef', tags:['cooked','veg-forward'],
    ingredients:['Berenjenas','Carne picada mixta (Mercadona)','Tomate frito Hacendado','Cebolla','Ajo','Queso rallado Hacendado','Orégano'],
    kcal:490, protein:30, carbs:28, fat:26, gazpacho:true },
  { id:'pasta-boloñesa', name:'Pasta a la boloñesa', prep:25, proteinType:'beef', tags:['cooked','classic'],
    ingredients:['Pasta (Hacendado)','Carne picada mixta (Mercadona)','Tomate frito Hacendado','Cebolla','Zanahoria','Ajo','Vino tinto','Queso parmesano'],
    kcal:610, protein:34, carbs:66, fat:22, gazpacho:false },
  { id:'champiñones-rellenos', name:'Champiñones rellenos de jamón y queso', prep:25, proteinType:'cured', tags:['cooked','veg-forward','protein'],
    ingredients:['Champiñones grandes (Mercadona)','Jamón serrano en taquitos','Queso de untar Hacendado','Ajo','Perejil','Aceite de oliva virgen extra'],
    kcal:390, protein:22, carbs:10, fat:28, gazpacho:true },
  { id:'lomo-cerdo-pimenton', name:'Lomo de cerdo al pimentón con arroz', prep:25, proteinType:'pork', tags:['cooked','protein'],
    ingredients:['Lomo de cerdo en filetes (Mercadona)','Pimentón dulce y picante','Ajo','Vino blanco','Arroz redondo (Hacendado)','Aceite de oliva virgen extra'],
    kcal:540, protein:42, carbs:46, fat:20, gazpacho:false },
  { id:'ensalada-pasta-pollo', name:'Ensalada de pasta con pollo y pesto', prep:15, proteinType:'poultry', tags:['no-cook','quick'],
    ingredients:['Pasta cocida fría','Pechuga de pollo cocida (Mercadona, envasada)','Pesto Hacendado','Tomates cherry','Parmesano rallado','Rúcula'],
    kcal:530, protein:38, carbs:46, fat:20, gazpacho:false },
  { id:'arroz-leche-pollo', name:'Arroz con leche de coco y pollo asiático', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Arroz jazmín (Hacendado)','Pechuga de pollo en tiras','Leche de coco Hacendado','Curry verde en pasta o polvo','Espinacas baby','Cilantro'],
    kcal:570, protein:38, carbs:56, fat:20, gazpacho:false },
  { id:'albondigas-almendras', name:'Albóndigas en salsa de almendras', prep:30, proteinType:'pork', tags:['cooked','classic'],
    ingredients:['Carne picada de cerdo (Mercadona)','Almendras molidas (Hacendado)','Ajo','Vino blanco','Caldo de pollo','Perejil','Pan rallado','Huevo'],
    kcal:560, protein:32, carbs:22, fat:36, gazpacho:true },
  { id:'ensalada-judias-atun', name:'Ensalada de judías verdes y atún', prep:15, proteinType:'fish', tags:['cooked','light','protein'],
    ingredients:['Judías verdes (Mercadona, bolsa congelada)','Atún en aceite de oliva (lata)','Tomate de ensalada','Cebolla morada','Aceite de oliva virgen extra','Vinagre de Módena'],
    kcal:400, protein:30, carbs:24, fat:18, gazpacho:true },
  { id:'salmon-miso-brócoli', name:'Salmón glaseado con miso y brócoli', prep:25, proteinType:'fish', tags:['cooked','protein','omega3'],
    ingredients:['Lomos de salmón (Mercadona)','Pasta de miso (herboristería o grandes superficies)','Miel Hacendado','Salsa de soja','Brócoli','Arroz o fideos'],
    kcal:550, protein:42, carbs:38, fat:24, gazpacho:false },
  { id:'revuelto-bacalao-pimiento', name:'Revuelto de bacalao y pimiento asado', prep:20, proteinType:'fish', tags:['cooked','classic','protein'],
    ingredients:['Bacalao desalado en migas (Mercadona)','Pimiento rojo asado (bote)','Huevos','Ajo','Aceite de oliva virgen extra','Perejil'],
    kcal:410, protein:32, carbs:10, fat:24, gazpacho:true },
  { id:'pasta-salchicha-tomate', name:'Pasta con salchicha y tomate picante', prep:20, proteinType:'pork', tags:['cooked','quick'],
    ingredients:['Pasta (Hacendado)','Salchicha fresca (Mercadona)','Tomate frito Hacendado','Ajo','Guindilla','Queso rallado Hacendado'],
    kcal:620, protein:30, carbs:66, fat:24, gazpacho:false },
  { id:'vieiras-plancha', name:'Vieiras o volandeiras a la plancha', prep:12, proteinType:'seafood', tags:['cooked','quick','seafood'],
    ingredients:['Volandeiras o vieiras (Mercadona, congeladas)','Mantequilla','Ajo','Limón','Perejil','Pan de acompañamiento'],
    kcal:380, protein:28, carbs:14, fat:18, gazpacho:true },
  { id:'pollo-zaatar', name:'Pollo marinado con zaatar y yogur', prep:25, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Muslos de pollo deshuesados (Mercadona)','Yogur natural Hacendado','Zaatar (herboristería)','Limón','Ajo','Pepino y pan de pita'],
    kcal:510, protein:42, carbs:24, fat:24, gazpacho:false },
  { id:'lentejas-verduras-curry', name:'Lentejas rojas con curry y coco', prep:25, proteinType:'legume', tags:['cooked','legume','warming'],
    ingredients:['Lentejas rojas (Hacendado)','Leche de coco Hacendado','Cebolla','Ajo','Jengibre en polvo','Curry en polvo','Tomate frito','Arroz basmati'],
    kcal:540, protein:26, carbs:72, fat:16, gazpacho:false },
  { id:'pez-espada-plancha', name:'Pez espada a la plancha con salsa verde', prep:15, proteinType:'fish', tags:['cooked','quick','protein'],
    ingredients:['Filetes de pez espada (Mercadona)','Perejil','Ajo','Limón','Aceite de oliva virgen extra','Alcaparras (bote)'],
    kcal:420, protein:40, carbs:4, fat:26, gazpacho:true },
  { id:'pollo-verduras-horno', name:'Pollo y verduras al horno de bandeja', prep:30, proteinType:'poultry', tags:['cooked','protein','batch'],
    ingredients:['Muslos de pollo (Mercadona)','Patatas','Pimiento','Cebolla','Ajo','Aceite de oliva virgen extra','Romero y pimentón'],
    kcal:580, protein:40, carbs:36, fat:28, gazpacho:true },
  { id:'ensalada-cesar-pollo', name:'Ensalada César con pollo a la plancha', prep:15, proteinType:'poultry', tags:['cooked','quick','classic'],
    ingredients:['Pechuga de pollo','Lechuga romana (bolsa Mercadona)','Queso parmesano rallado','Salsa César Hacendado (bote)','Picatostes integrales'],
    kcal:480, protein:40, carbs:24, fat:24, gazpacho:false },
  { id:'chuletas-cerdo-manzana', name:'Chuletas de cerdo con manzana y cebolla caramelizada', prep:25, proteinType:'pork', tags:['cooked','protein'],
    ingredients:['Chuletas de cerdo (Mercadona)','Manzana','Cebolla','Azúcar moreno Hacendado','Mantequilla','Vino blanco'],
    kcal:540, protein:38, carbs:28, fat:30, gazpacho:false },
  { id:'garbanzos-bacalao', name:'Potaje de garbanzos y bacalao', prep:25, proteinType:'legume', tags:['cooked','legume','classic'],
    ingredients:['Garbanzos cocidos (bote Hacendado)','Bacalao desalado en migas (Mercadona)','Espinacas frescas','Tomate frito','Ajo','Pimentón','Aceite de oliva'],
    kcal:500, protein:34, carbs:50, fat:16, gazpacho:false },
  { id:'fideos-caldo-pollo', name:'Fideos con caldo de pollo y verduras', prep:20, proteinType:'poultry', tags:['cooked','warming','quick'],
    ingredients:['Fideos sopa (Hacendado)','Caldo de pollo (brik Hacendado)','Zanahoria','Pechuga de pollo en dados','Puerro','Perejil'],
    kcal:400, protein:28, carbs:46, fat:10, gazpacho:false },
  { id:'rollitos-primavera-pollo', name:'Rollitos de lechuga con pollo y mango', prep:15, proteinType:'poultry', tags:['cooked','light','quick'],
    ingredients:['Pechuga de pollo cocida','Hojas de lechuga grandes (iceberg)','Mango','Zanahoria rallada','Salsa de soja','Jengibre en polvo','Sésamo'],
    kcal:380, protein:32, carbs:28, fat:10, gazpacho:false },
  { id:'rape-plancha-verduras', name:'Rape a la plancha con verduras al vapor', prep:20, proteinType:'fish', tags:['cooked','protein','light'],
    ingredients:['Cola de rape en rodajas (Mercadona)','Brócoli o judías verdes','Ajo','Limón','Aceite de oliva virgen extra','Sal y pimienta'],
    kcal:390, protein:40, carbs:12, fat:18, gazpacho:true },
  { id:'cuscus-verduras-pollo', name:'Cuscús con verduras y pollo', prep:20, proteinType:'poultry', tags:['cooked','quick','balanced'],
    ingredients:['Cuscús (Hacendado)','Pechuga de pollo','Zanahoria','Calabacín','Cebolla','Ras el hanout o cúrcuma','Caldo de pollo','Pasas opcionales'],
    kcal:520, protein:38, carbs:56, fat:14, gazpacho:false },
  { id:'tortillitas-camarones', name:'Tortillitas de camarones estilo gaditano', prep:20, proteinType:'seafood', tags:['cooked','classic','seafood'],
    ingredients:['Camarones o gambas pequeñas (Mercadona)','Harina de garbanzos','Cebolleta','Perejil','Sal','Aceite de girasol para freír'],
    kcal:460, protein:26, carbs:38, fat:22, gazpacho:true },
  { id:'ensalada-griega', name:'Ensalada griega completa', prep:10, proteinType:'cheese', tags:['no-cook','light','summer'],
    ingredients:['Tomate de ensalada','Pepino','Cebolla morada','Aceituna negra (Mercadona)','Queso feta (Mercadona)','Orégano','Aceite de oliva virgen extra'],
    kcal:380, protein:14, carbs:22, fat:26, gazpacho:true },
  { id:'lubina-horno', name:'Lubina al horno con limón y hierbas', prep:30, proteinType:'fish', tags:['cooked','protein','classic'],
    ingredients:['Lubina entera o filetes (Mercadona)','Limón','Ajo','Romero y tomillo','Aceite de oliva virgen extra','Patatas opcionales'],
    kcal:430, protein:40, carbs:10, fat:24, gazpacho:true },
  { id:'pollo-almendras', name:'Pollo en salsa de almendras', prep:30, proteinType:'poultry', tags:['cooked','protein','classic'],
    ingredients:['Muslos de pollo deshuesados (Mercadona)','Almendras crudas (Hacendado)','Cebolla','Ajo','Vino blanco','Azafrán','Caldo de pollo'],
    kcal:560, protein:44, carbs:14, fat:32, gazpacho:false },
  { id:'pasta-gambas-crema', name:'Pasta con gambas y salsa de nata', prep:20, proteinType:'seafood', tags:['cooked','quick'],
    ingredients:['Pasta (Hacendado)','Gambas peladas congeladas','Nata para cocinar Hacendado','Ajo','Perejil','Queso parmesano rallado'],
    kcal:590, protein:30, carbs:62, fat:24, gazpacho:false },
  { id:'guisantes-jamon-huevo', name:'Guisantes salteados con jamón y huevo', prep:15, proteinType:'cured', tags:['cooked','quick','classic'],
    ingredients:['Guisantes congelados (Hacendado)','Jamón serrano en taquitos','Huevos','Ajo','Aceite de oliva virgen extra'],
    kcal:420, protein:28, carbs:30, fat:20, gazpacho:true },
  { id:'muslos-pollo-cerveza', name:'Muslos de pollo a la cerveza', prep:30, proteinType:'poultry', tags:['cooked','classic'],
    ingredients:['Muslos de pollo (Mercadona)','Cerveza rubia (33cl)','Cebolla','Ajo','Laurel','Tomillo','Aceite de oliva virgen extra'],
    kcal:520, protein:40, carbs:14, fat:28, gazpacho:true },
  { id:'brochetas-cerdo-pimiento', name:'Brochetas de cerdo y pimiento', prep:20, proteinType:'pork', tags:['cooked','quick','protein'],
    ingredients:['Lomo de cerdo en tacos (Mercadona)','Pimiento rojo y verde','Cebolla','Aceite de oliva virgen extra','Sal y especias BBQ'],
    kcal:470, protein:38, carbs:16, fat:26, gazpacho:true },
  { id:'pasta-atun-pimiento-asado', name:'Pasta con atún y pimiento asado', prep:15, proteinType:'fish', tags:['cooked','quick'],
    ingredients:['Pasta (Hacendado)','Atún en aceite de oliva (lata)','Pimiento rojo asado (bote Mercadona)','Ajo','Tomate cherry','Aceitunas negras'],
    kcal:530, protein:28, carbs:62, fat:16, gazpacho:false },
  { id:'tofu-verduras', name:'Tofu salteado con verduras y salsa de soja', prep:20, proteinType:'veg', tags:['cooked','veg-forward','protein'],
    ingredients:['Tofu firme (Mercadona o herboristería)','Pimiento','Calabacín','Cebolla','Salsa de soja','Aceite de sésamo','Arroz jazmín (Hacendado)'],
    kcal:440, protein:24, carbs:46, fat:18, gazpacho:false },
  { id:'pimientos-rellenos-atun', name:'Pimientos rellenos de atún y arroz', prep:30, proteinType:'fish', tags:['cooked','classic'],
    ingredients:['Pimientos rojos o verdes','Arroz redondo (Hacendado)','Atún en aceite de oliva (lata)','Tomate frito','Cebolla','Queso rallado Hacendado'],
    kcal:490, protein:26, carbs:56, fat:16, gazpacho:true },
  { id:'carne-picada-especias', name:'Kofta de carne picada con ensalada', prep:20, proteinType:'beef', tags:['cooked','protein'],
    ingredients:['Carne picada mixta (Mercadona)','Comino','Cilantro en polvo','Ajo','Cebolla rallada','Pan de pita','Lechuga y tomate','Yogur con ajo'],
    kcal:530, protein:36, carbs:36, fat:26, gazpacho:false },
  { id:'ensalada-beet-queso', name:'Ensalada de remolacha y queso de cabra', prep:10, proteinType:'cheese', tags:['no-cook','light'],
    ingredients:['Remolacha cocida (Mercadona, bolsa)','Queso de cabra en rulo (Mercadona)','Nueces peladas','Rúcula o espinacas baby','Vinagreta balsámica'],
    kcal:390, protein:14, carbs:30, fat:24, gazpacho:false },
  { id:'pasta-espinacas-ricotta', name:'Pasta con espinacas y ricotta', prep:20, proteinType:'cheese', tags:['cooked','veg-forward'],
    ingredients:['Pasta (Hacendado)','Espinacas frescas (bolsa)','Ricotta o queso de untar Hacendado','Ajo','Nuez moscada','Queso parmesano rallado'],
    kcal:540, protein:22, carbs:66, fat:20, gazpacho:false },
  { id:'bacalao-ajoarriero', name:'Bacalao al ajoarriero', prep:25, proteinType:'fish', tags:['cooked','classic','protein'],
    ingredients:['Bacalao desalado (Mercadona)','Tomate frito Hacendado','Pimiento rojo asado (bote)','Ajo','Pimentón','Aceite de oliva virgen extra'],
    kcal:430, protein:38, carbs:18, fat:20, gazpacho:true },
  { id:'pollo-feta-aceitunas', name:'Pollo al horno con feta y aceitunas', prep:30, proteinType:'poultry', tags:['cooked','protein'],
    ingredients:['Pechuga de pollo (Mercadona)','Queso feta','Aceitunas kalamata (Mercadona)','Tomates cherry','Orégano','Aceite de oliva virgen extra','Ajo'],
    kcal:510, protein:46, carbs:10, fat:30, gazpacho:true },
  { id:'arroz-verduras-huevo', name:'Arroz salteado con verduras y huevo', prep:20, proteinType:'egg', tags:['cooked','quick','veg-forward'],
    ingredients:['Arroz cocido (sobrante o Mercadona, bolsita)','Huevos','Guisantes congelados','Zanahoria','Cebolla','Salsa de soja','Aceite de girasol'],
    kcal:490, protein:20, carbs:64, fat:18, gazpacho:false },

  // ── NEW MEALS — 35+ MIN ───────────────────────────────────────────────
  { id:'estofado-ternera', name:'Estofado de ternera con patatas', prep:50, proteinType:'beef', tags:['cooked','slow','batch'],
    ingredients:['Carne de ternera para guisar (Mercadona)','Patatas','Zanahoria','Cebolla','Ajo','Vino tinto','Tomate frito','Laurel y tomillo'],
    kcal:600, protein:40, carbs:42, fat:26, gazpacho:false },
  { id:'pollo-asado-horno', name:'Pollo entero asado al horno', prep:60, proteinType:'poultry', tags:['cooked','slow','weekend','batch'],
    ingredients:['Pollo entero (Mercadona)','Ajo','Romero y tomillo','Limón','Aceite de oliva virgen extra','Patatas de guarnición'],
    kcal:620, protein:46, carbs:22, fat:36, gazpacho:true },
  { id:'fabada-rapida', name:'Fabada asturiana rápida', prep:40, proteinType:'legume', tags:['cooked','slow','legume','batch'],
    ingredients:['Fabas grandes en bote (Hacendado)','Chorizo Hacendado','Morcilla (Mercadona)','Panceta ahumada','Pimentón','Laurel','Azafrán'],
    kcal:640, protein:32, carbs:54, fat:30, gazpacho:false },
  { id:'caldo-pollo-casero', name:'Caldo de pollo casero con fideos', prep:60, proteinType:'poultry', tags:['cooked','slow','batch','warming'],
    ingredients:['Carcasas o contramuslos de pollo (Mercadona)','Zanahoria','Puerro','Apio','Cebolla','Fideos sopa','Sal y pimienta'],
    kcal:380, protein:28, carbs:36, fat:14, gazpacho:false },
  { id:'arroz-caldoso-marisco', name:'Arroz caldoso de marisco', prep:40, proteinType:'seafood', tags:['cooked','slow','weekend'],
    ingredients:['Arroz redondo (Hacendado)','Gambas enteras (Mercadona)','Mejillones','Caldo de pescado','Tomate','Pimentón','Azafrán','Ajo'],
    kcal:580, protein:32, carbs:68, fat:16, gazpacho:false },
];

// Approx kcal/macro multipliers for the fixed size presets — applied on
// top of the "regular" numbers above, then rounded for display.
const KITCHEN_SIZE_MULT = { small:0.75, regular:1, large:1.35 };
const KITCHEN_SIZE_LABEL = { small:'Small', regular:'Regular', large:'Large' };
function scaledMacro(meal, field) {
  return Math.round(meal[field] * KITCHEN_SIZE_MULT[S.kitchen.size || 'regular']);
}

// Pre-made bundles — curated by hand rather than built-your-own, so this
// stays a single small <select> instead of a whole extra UI. Each is 3
// meals with a reason behind the grouping (varied protein, fastest-spoiling
// things grouped so nothing sits in the fridge too long).
const KITCHEN_BUNDLES = [
  // ── No-cook / assembly ───────────────────────────────────────────────
  { id:'assembly-classics', label: 'Jamón, salmón ahumado, queso y garbanzos',
    mealIds: ['charcuteria','salmon-ahumado','atun-garbanzo'] },
  { id:'no-cook-var', label: 'Pollo asado, huevos rellenos y ensalada griega',
    mealIds: ['pollo-asado-bolsa','huevos-rellenos','ensalada-griega'] },
  { id:'conservas-board', label: 'Conservas del mar, bonito y sardinas',
    mealIds: ['conservas-mar','bonito-pimiento-tomate','tosta-sardinas'] },
  { id:'quick-wrap-tosta', label: 'Wrap de pavo, bocadillo de jamón y tabla de quesos',
    mealIds: ['wrap-pavo-aguacate','bocadillo-serrano-tomate','queso-membrillo'] },
  { id:'legume-cold', label: 'Garbanzos, lentejas y judías frías',
    mealIds: ['ensalada-garbanzos-espinacas','ensalada-lentejas-feta','ensalada-judias-atun'] },

  // ── Quick weeknight (≤20 min) ─────────────────────────────────────────
  { id:'quick-protein', label: 'Pollo, gambas al ajillo y pez espada',
    mealIds: ['pollo-plancha-verduras','gambas-ajo','pez-espada-plancha'] },
  { id:'quick-pasta', label: 'Pasta con atún, carbonara y gambas con nata',
    mealIds: ['pasta-tomate-atun','pasta-carbonara-ligera','pasta-gambas-crema'] },
  { id:'quick-egg', label: 'Tortilla francesa, revuelto de gambas y huevos rotos',
    mealIds: ['tortilla-francesa-ensalada','revuelto-gambas-setas','huevos-rotos-jamon'] },
  { id:'quick-fish', label: 'Merluza, salmón y calamares',
    mealIds: ['revuelto-bacalao-pimiento','calamar-plancha','salmon-plancha-patata'] },
  { id:'quick-mixed', label: 'Pollo al limón, mejillones y lentejas rápidas',
    mealIds: ['pechuga-limon-alcaparras','mejillones-vapor','lentejas-rapidas'] },

  // ── Seafood-forward ───────────────────────────────────────────────────
  { id:'seafood-classic', label: 'Merluza, arroz con gambas y fideuà',
    mealIds: ['merluza-papillote','arroz-verduras-gambas','fideuà-rapida'] },
  { id:'seafood-plancha', label: 'Sepia, rape y vieiras a la plancha',
    mealIds: ['sepia-plancha-alioli','rape-plancha-verduras','vieiras-plancha'] },
  { id:'seafood-pasta-rice', label: 'Espaguetis con almejas, arroz negro y sopa de pescado',
    mealIds: ['espaguetis-almejas','arroz-negro-sepia','sopa-pescado'] },

  // ── Higher protein ────────────────────────────────────────────────────
  { id:'high-protein-chicken', label: 'Pollo con feta, pollo zaatar y muslos a la cerveza',
    mealIds: ['pollo-feta-aceitunas','pollo-zaatar','muslos-pollo-cerveza'] },
  { id:'high-protein-mixed', label: 'Solomillo de cerdo, salmón miso y pollo mostaza',
    mealIds: ['solomillo-cerdo-manzana','salmon-miso-brócoli','pollo-mostaza-miel'] },
  { id:'high-protein-plancha', label: 'Ternera, pez espada y pechuga al limón',
    mealIds: ['ternera-plancha-pisto','pez-espada-plancha','pechuga-limon-alcaparras'] },

  // ── Vegetarian / legume-forward ───────────────────────────────────────
  { id:'veg-legume', label: 'Garbanzos con espinacas, lentejas curry y tofu',
    mealIds: ['garbanzos-espinacas-huevo','lentejas-verduras-curry','tofu-verduras'] },
  { id:'veg-egg-pasta', label: 'Pisto con huevo, pasta espinacas y arroz salteado',
    mealIds: ['pisto-huevo','pasta-espinacas-ricotta','arroz-verduras-huevo'] },
  { id:'veg-comfort', label: 'Alubias, fabada y lentejas tradicionales',
    mealIds: ['alubias-chorizo','fabada-rapida','lentejas-tradicionales'] },

  // ── Batch / weekend ───────────────────────────────────────────────────
  { id:'weekend-paella', label: 'Paella, arroz caldoso y pollo asado entero',
    mealIds: ['paella-mixta','arroz-caldoso-marisco','pollo-asado-horno'] },
  { id:'weekend-slow', label: 'Estofado de ternera, fabada y caldo de pollo',
    mealIds: ['estofado-ternera','fabada-rapida','caldo-pollo-casero'] },
  { id:'batch-cook', label: 'Pollo al horno, lentejas tradicionales y albóndigas',
    mealIds: ['pollo-verduras-horno','lentejas-tradicionales','albondigas-tomate'] },

  // ── Surprise ──────────────────────────────────────────────────────────
  { id:'random', label: '🎲 Surprise me' }
];

const KITCHEN_TIERS = [
  { key:'ten',  label:'10 min',  test: m => m.prep <= 12 },
  { key:'mid20', label:'20 min', test: m => m.prep > 12 && m.prep <= 22 },
  { key:'mid30', label:'30 min', test: m => m.prep > 22 && m.prep < 35 },
  { key:'slow', label:'35+ min', test: m => m.prep >= 35 }
];
